// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';


/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsJUwv0xhlLUsD7GVw7b-nHx4BFOP0LAs',
    appId: '1:1093127153668:web:04eea724054700d0fbad51',
    messagingSenderId: '1093127153668',
    projectId: 'reality-check-app-69edc',
    authDomain: 'reality-check-app-69edc.firebaseapp.com',
    storageBucket: 'reality-check-app-69edc.firebasestorage.app',
    measurementId: 'G-21W3FW9T8E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB28Oyqulwbb7oGvmVe6-jyyASyKiV_bkw',
    appId: '1:1093127153668:android:baa327f7de5b2209fbad51',
    messagingSenderId: '1093127153668',
    projectId: 'reality-check-app-69edc',
    storageBucket: 'reality-check-app-69edc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3A56YQU6XW09OnYQ0a634TSk9y6CLvjE',
    appId: '1:1093127153668:ios:ee73c405eaf0d467fbad51',
    messagingSenderId: '1093127153668',
    projectId: 'reality-check-app-69edc',
    storageBucket: 'reality-check-app-69edc.firebasestorage.app',
    iosBundleId: 'com.example.realityTestApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3A56YQU6XW09OnYQ0a634TSk9y6CLvjE',
    appId: '1:1093127153668:ios:ee73c405eaf0d467fbad51',
    messagingSenderId: '1093127153668',
    projectId: 'reality-check-app-69edc',
    storageBucket: 'reality-check-app-69edc.firebasestorage.app',
    iosBundleId: 'com.example.realityTestApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsJUwv0xhlLUsD7GVw7b-nHx4BFOP0LAs',
    appId: '1:1093127153668:web:e88eefc405218f63fbad51',
    messagingSenderId: '1093127153668',
    projectId: 'reality-check-app-69edc',
    authDomain: 'reality-check-app-69edc.firebaseapp.com',
    storageBucket: 'reality-check-app-69edc.firebasestorage.app',
    measurementId: 'G-FCKTZLLKW6',
  );

}